const { getRandomCourses } = require("../../src/utils/course")

describe('Link between Offerings and Schedule', function() {
  it('Add from Schedule, delete from Offerings', function() {
    cy.visit('')
    const course = getRandomCourses(1)[0]
    cy.get('.fa-expand')
      .click()
    cy.get('#search-input')
      .type(course.id + '{enter}', {force: true})
    cy.contains(course.id)
      .should('exist')
    cy.get('.navbar-btn')
      .get('.fa-list-alt')
      .click()
    cy.contains(course.id)
      .parent()
      .parent()
      .get('.cta')
      .contains('Remove')
      .click()
    cy.contains(course.id)
      .parent()
      .parent()
      .get('.cta')
      .contains('Add')
    cy.get('.navbar-btn')
      .get('.fa-calendar')
      .click()
    cy.contains(course.id)
      .should('not.exist')
  })
})