const { getRandomCourses } = require("../../src/utils/course")

describe.skip('Link between Offerings and Schedule', function() {
  it('Add from Schedule, delete from Offerings', function() {
    cy.visit('')
    const course = getRandomCourses(1)[0]
    cy.get('#search-input')
      .type(course.id + '{enter}', {force: true})
    cy.contains(course.id)
      .should('exist')
    cy.get('.navbar')
      .contains('Courses')
      .click()
    cy.contains(course.id)
      .parent()
      .parent()
      .get('.cta')
      .contains('Remove') // ERROR: Two buttons!
      .click()
    cy.contains(course.id)
      .parent()
      .parent()
      .get('.cta')
      .contains('Add')
    cy.get('.navbar')
      .contains('Schedule')
      .click()
    cy.contains(course.id)
      .should('not.exist')
  })
})